server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
#    active: aggregation
    active: dev
  data:
    redis:
      host: 172.27.212.83
      port: 6379
      password: 123321
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
