server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 172.27.212.83
      port: 6379
      password: 123321
  kafka:
    bootstrap-servers: 172.27.212.83:9092
    consumer:
      group-id: short-link:stats-stream:only-group
      auto-offset-reset: earliest
    topic:
      short-link-stats: short-link:stats-stream

  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#message-queue：
#  select： redis

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 8b4a740504bbf370997c966a3db9fe80
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml